### ISSUE TITLE
No route found for "GET /sso/login/"

### ISSUE THREAD

**Issue by timothyjeffcoat** [korotovsky/SingleSignOnIdentityProviderBundle#7]
I wonder if you could tell me why I would get this error?

No route found for "GET /sso/login/"

As far as I can tell I have configured the identity provider as instructed.

Any help is much appreciated.

Thanks

**Comment by korotovsky** [comment]
Did you include this routing into your `routing.yml`?

```yaml
# app/config/routing.yml:
sso:
    resource: .
    type:     sso
```

Could you also paste your `app/cache/dev/appDevUrlMatcher.php` file to gist?
